version: '3.3'
services:
  postgredb:
    container_name: postgres-db
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"